### ISSUE TITLE
UCUM as base for unit definitions?

### ISSUE THREAD

**Issue by paparomeo** [python-quantities/python-quantities#38]
Would there be any interest in using 'The Unified Code for Units of Measure' (http://unitsofmeasure.org/) as the reference for unit definitions? Specifically generating the unit definition source files from the following XML document: http://aurora.regenstrief.org/~ucum/ucum-essence.xml, taking care of course to maintain API compatibility.

I find myself needing a units of measure / quantities Python package, that will provide the functionality defined in the UCUM, but not really wanting to create yet another Python units package.

Any thoughts appreciated.

**Comment by rstuven** [comment]
Regarding UCUM relevance, just wanted to point out that this year the [Java Specification Request 363 (Units of Measurements API)](https://jcp.org/en/jsr/detail?id=363), which supports UCUM, has been approved. The [specification](https://docs.google.com/document/d/12KhosAFriGCczBs6gwtJJDfg_QlANT92_lhxUWO2gCY/) states: 
> Healthcare providers and organizations around the world made UCUM a widely used standard for their communication, especially HL7 or large globally operating institutions like WHO or CDC [...] who are in need of sustainable and reliable exchange for healthcare and patient information.

**Comment by keilw** [comment]
Thanks, I'm aware of that since I am one of its Spec Leads;)

**Comment by garretwilson** [comment]
>  ... Java Specification Request 363 (Units of Measurements API), which supports UCUM ...

... except that UCUM support has been pulled from the JSR 363 API itself, and even pulled from the reference implementation, and handed off to some Eclipse project that has no definite timeline or even guarantee of implementing UCUM.

There is so much erroneous information in this area floating around on the Internet. When it is never corrected, it makes it difficult for us trying to make decisions on what is the best standard (and API) to use for unit representation.

**Comment by keilw** [comment]
Yes, like a "Bowling Green Massacre" or "What happened in Sweden last night" ;-D

To provide some correction and real facts instead of fake news, @rstuven simply pointed to the Spec of JSR 363 and drawn his conclusion, that JSR 363 itself would directly support or implement UCUM. That's not the case. We quoted representative use cases from health, IoT or DevOps. Some now use JSR 363 like https://github.com/performancecopilot/parfait, others still use JSR 275 or the intermediary https://github.com/unitsofmeasurement/uom-legacy. The latter is used by Eclipse UOMo UCUM. Nothing was "transferred to Eclipse" UOMo UCUM was always there since the days of OHF which is archived now. UOMo UCUM is likely the only full Open Source UCUM implementation you may find out there. It passes all the necessary UCUM tests. It does not implement JSR 363 right now, but from a UCUM point that's irrelevant, if it does this on top of JSR 275, https://github.com/unitsofmeasurement/uom-legacy or JSR 363.

There are several reasons why UOMo UCUM must remain at Eclipse, probably among the most severe a "Crown Copyright" from the Australian initial authors which lasts almost as long as the English monarchy did so far. And is meant to protect software being used in public services or healthcare from being taken away. So maybe the mentioned Trump can take Healthcare away from Millions of Americans, but even if say UOMo and UOMo UCUM were archived at Eclipse Foundation, they won't be taken away or turned into proprietary closed source products because of that ;-)

**Comment by garretwilson** [comment]
> Nothing was "transferred to Eclipse" UOMo UCUM was always there since the days of OHF which is archived now.

Here I was referring to the fact that @keilw you used to provide several UCUM implementations (however incomplete) of JSR 363 (and even pointed people to them), but then you pulled those implementations; and when asked about them, you started pointing people to OUMo. So the _responsibility_ for implementation has been passed from JSR 275 (which actually had a UCUM `UnitFormat` retrieval method), to JSR 363, to https://github.com/unitsofmeasurement/uom-systems , and now to UOMo --- which as you point out is not JSR 363 compliant, and as I point out isn't even available on Maven. So the buck keeps getting passed, but the bill never gets paid. I personally think it's a mess for no reason.

I'm not trying to be grouchy, I'm just trying to implement a lab system for a huge genetics company, and settle on a standard unit representation and API. If one reads here and there on the Internet, everybody makes casual references that make it seem we can just use UCUM with JSR 363 and everybody will be happy. _And that's how it should be!_ I'm just trying to clarify that this characterization isn't even close to the real world, and in fact the real situation is hardly usable. (Just this morning for example I creating a kludge wrapper around your `tec.uom:uom-se:1.0.4` JSR 363 implementation just to convert "ml" to "mL" and back when serializing and parsing, in order to get UCUM compliance. Yuck. (No, I'm not interested in UOMo if it doesn't implement JSR 363 and if it isn't on Maven.)

I don't say all this to discourage @paparomeo from implementing UCUM in `python-quantities` --- in fact just the opposite. (Our project will need Python implementation as well soon.) I'm trying to explain to people that the real-life situation is a mess, and we need more people to step up to the plate and actually implement the specification already so we can get some semblance of interoperability.

Please take this as constructive. I'm wanting to do my part to help, and @keilw I greatly appreciate your responses and feedback in all these threads.

**Comment by keilw** [comment]
@garretwilson Thanks for the detailed reply. 
Glad you got a solution for your urgent use case on top of uom-se. If it is corporate closed-source, no worries, then nobody will ask you to share it;-) Otherwise we'd be happy to look at the right place. If you only need to cover a small subset of UCUM like `LITRE `or `Volume`, it is fair to just keep it that way. Neither JSR 275 nor JScience (where we inherited most UCUM references from) ever had time or other resources to put all UCUM units into their implementation. 
Actually if you check https://java.net/projects/jscience/sources/svn/content/trunk/jscience/physics/src/main/java/org/jscience/physics/unit/UCUM.java?rev=696 in theory the paragraphs up to 4.6 could be complete, but I cannot guarantee it reflected the full UCUM system even at the time.

Actually
```
/////////////////////////////////////////////////////////
// SECTIONS §41-§43 skipped; implement later if needed //
/////////////////////////////////////////////////////////
```
Confirms, at least some parts of the UCUM spec were left out.

Would you be willing to help completing it if we put the UCUM module back to https://github.com/unitsofmeasurement/uom-systems
at least for Java SE?

It was not removed for legal or licensing reasons (as ISO 80000 where the content of the catalogue seems subject to ISO license terms and cannot simply be put into an Open Source project, we investigate ways with Oracle it it might be possible, but for now ISO80k is out of scope) but to avoid an incomplete picture of UCUM. If someone can help us complete it, happy to put it back.

**Comment by garretwilson** [comment]
> Would you be willing to help completing it if we put the UCUM module back to https://github.com/unitsofmeasurement/uom-systems
at least for Java SE?

Yes!!! I was five minutes away from starting to write up a task for one of my developers to investigate implementing JSR 363 from scratch, or for porting the OUMo code to JSR 363. Continuing your work would certainly be a better avenue than either of the other options.

We should probably move the discussion to somewhere more appropriate. Do you want to create a new issue on `uom-systems`? And a related question is where this would go---glumping together several projects in one Git repository is not my first choice (although in Subversion days I put almost everything into one project, and then spent years teasing them apart when converting to Git). Let me know where we should discuss this further. Thanks.

**Comment by keilw** [comment]
I created https://github.com/unitsofmeasurement/uom-systems/issues/58 for this. 
Based on what was there (ported JScience 5) I'll add a ucum-java8 module (right now the variants are all based on ResourceBundle and SymbolMap in uom-se, so currently it is restricted to Java SE) and happy about PRs based on the issue ticket.

**Comment by stuz5000** [comment]
I'm curious, does the UCUM spec allow interpretation of "mm/Hg" (common measure) as an alternative to "m/Hg" (the metric x10^1 measure defined in in the http://unitsofmeasure.org/ucum-essence.xml spec). The former is not explicitly listed in the spec, however, the spec also doesn't seem to indicate that "m/Hg" is composed of a "m" numerator -- from which we'd be able to reason that "mm/Hg" and "micro m/Hg" are valid conversions.

**Comment by tdunning** [comment]
Very late response to @stuz5000 

Yes, UCUM allows for precisely that measurement in the form you suggest. The first `m` is a prefix (milli) and the second refers to a meter.

This is a specific example at http://download.hl7.de/documents/ucum/ucumdata.html
